version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsospace-landing-page
    ports:
      - "5055:3000"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge